//! The `emit` stage: Core IR + plan → a generated Rust cargo workspace.
//!
//! Approach (OWNER.md contract, Ring0_Build_Plan §1.8): **quote + prettyplease
//! into a generated cargo workspace, one module per relation (store + indices)
//! and per rule (one delta fn per delta source), with `#[deny(...)]` determinism
//! headers.** `brix explain --rust <Rule>` prints the module for one rule; the
//! flagship's whole generated workspace is an `insta` snapshot so codegen drift
//! is visible in review (§1.8).
//!
//! Pass 1 (this stage) is where *all* semantics live (Part XXVIII §28.1):
//! backends, opt levels, and targets change cost, never any observable value. So
//! the generated code is a faithful, boring translation — the determinism header
//! is what mechanically holds the line (no `HashMap`, no floats off the strict
//! path, etc.) inside generated crates too.
//!
//! ## Status
//!
//! The real column/row monomorphization consumes `brix-ir`'s typed nodes, which
//! land in a sibling lane. Until then this stage operates on the small
//! [`RelationDesc`]/[`RuleDesc`] descriptors below — enough to exercise and
//! snapshot the codegen *shape* (module layout, naming, the deny header, the
//! delta-fn-per-source structure) end to end with `quote`/`prettyplease`. When
//! brix-ir merges, the descriptors are populated from IR instead of by hand and
//! the token-emitting bodies fill in; the module boundaries do not move.

mod project;
mod rust_type;
mod workspace;

pub use project::{project, project_phased};
pub use rust_type::rust_type_of;
pub use workspace::{assemble_workspace, assemble_workspace_with_runtime, sanitize_crate_name};

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// A relation to generate a store module for. In v0 this is a hand-built
/// descriptor; post-brix-ir it is projected from a typed IR relation node.
#[derive(Clone, Debug)]
pub struct RelationDesc {
    /// Relation name as written in source, e.g. `OrderStatus`.
    pub name: String,
    /// Roles/columns in declaration order.
    pub columns: Vec<ColumnDesc>,
    /// Key column names (the `key(...)` modifier). Determines the store's primary
    /// index. Empty for a keyless ground relation.
    pub key: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct ColumnDesc {
    pub name: String,
    /// Rust type for the column, as a scaffold string (e.g. `"NodeId"`,
    /// `"i64"`). Post-brix-ir this is a resolved IR type lowered to Rust.
    pub rust_type: String,
}

/// A rule to generate delta functions for. One delta fn is emitted per delta
/// source (semi-naive evaluation, Ring0_Build_Plan §1.8 / Part XXVIII §28.1).
#[derive(Clone, Debug)]
pub struct RuleDesc {
    /// Rule/derived-relation name, e.g. `Waiting`.
    pub name: String,
    /// The relations this rule reads; each becomes a delta source and thus one
    /// `delta_from_*` function.
    pub delta_sources: Vec<String>,
    /// The relation this rule emits when it has a tuple head. `None` for
    /// node/mask heads, whose runtime lowering remains a separate path.
    pub target_relation: Option<String>,
    /// A mechanically verified identity rule: one edge read whose variable
    /// bindings are reproduced unchanged by a tuple head with the same role
    /// layout. This is the first native semantic delta shape; other rules
    /// stay fail-closed until their join plan is emitted.
    pub identity_source: Option<String>,
    /// Appendix-F phase assigned to this rule. Rules in one phase settle to a
    /// positive fixed point before any later phase sees their changes.
    pub phase: u32,
}

/// Rules that the current native runtime emitter cannot yet represent. A
/// successful build must register every rule; silently omitting a join, mask,
/// node, or expression rule would create a binary with observably wrong
/// semantics. The compiler therefore fails closed until each shape has a
/// proven runtime lowering.
pub fn unsupported_runtime_rules(rules: &[RuleDesc]) -> Vec<String> {
    rules
        .iter()
        .filter(|rule| rule.target_relation.is_none() || rule.identity_source.is_none())
        .map(|rule| rule.name.clone())
        .collect()
}

/// The determinism header stamped at the root of every generated crate. This is
/// the mechanical enforcement of the discipline inside generated code
/// (CONTRIBUTING.md "Determinism discipline (enforced mechanically)"): a
/// generated module that reaches for a `HashMap` fails to compile.
pub fn determinism_header() -> TokenStream {
    quote! {
        // @generated by brixc — do not edit. Pass 1 output (BrixMS -> Rust).
        // Determinism discipline (spec Part XXVIII §28.3, CONTRIBUTING.md):
        #![deny(unsafe_code)]
        #![deny(clippy::disallowed_types)] // HashMap/HashSet banned; observable order = canon byte order
        #![deny(clippy::float_arithmetic)] // no floats outside the strict-IEEE ops module
    }
}

/// Emit the store module for one relation: a row struct, a canon-ordered primary
/// store (`BTreeMap` — never `HashMap`, per the header this compiles under), and
/// the `RelationStore`-style accessors the runtime and reflection consume.
pub fn emit_relation_module(rel: &RelationDesc) -> TokenStream {
    let mod_name = format_ident!("rel_{}", to_snake(&rel.name));
    let row_ident = format_ident!("{}Row", to_pascal_ident(&rel.name));

    let fields = rel.columns.iter().map(|c| {
        let name = safe_ident(&to_snake(&c.name));
        let ty: TokenStream = c
            .rust_type
            .parse()
            .unwrap_or_else(|_| quote! { compile_error!("unresolved column type") });
        quote! { pub #name: #ty }
    });

    // The primary key type is a tuple of the key columns' types (or unit if the
    // relation is keyless — a keyless ground relation stores rows by their EdgeId
    // in the real runtime; the scaffold uses row insertion order via a Vec-backed
    // fallback documented inline).
    let key_types: Vec<TokenStream> = rel
        .key
        .iter()
        .filter_map(|k| rel.columns.iter().find(|c| &c.name == k))
        .map(|c| c.rust_type.parse().unwrap_or_else(|_| quote! { () }))
        .collect();
    let key_ty = if key_types.is_empty() {
        quote! { () }
    } else {
        quote! { ( #( #key_types ),* ) }
    };

    quote! {
        pub mod #mod_name {
            use super::*;
            use std::collections::BTreeMap;

            /// One hyperedge of `#row_ident`: roles are columns.
            #[derive(Clone, Debug, PartialEq)]
            pub struct #row_ident {
                #( #fields ),*
            }

            /// Canon-ordered primary store. Iteration order is canon byte order
            /// of the key (BTreeMap), which is what every observable order in a
            /// BrixMS semantic path must be.
            #[derive(Default)]
            pub struct Store {
                rows: BTreeMap<#key_ty, #row_ident>,
            }

            impl Store {
                pub fn new() -> Self {
                    Self::default()
                }

                /// Iterate rows in canonical order.
                pub fn iter(&self) -> impl Iterator<Item = &#row_ident> {
                    self.rows.values()
                }

                pub fn len(&self) -> usize {
                    self.rows.len()
                }

                pub fn is_empty(&self) -> bool {
                    self.rows.is_empty()
                }
            }
        }
    }
}

/// Emit the rule module: one `delta_from_<source>` function per delta source
/// (semi-naive). The bodies are `todo!()` placeholders until brix-ir supplies the
/// join plan; the *structure* — a function per source, taking a typed delta batch
/// and returning emissions — is the stable contract the delta ABI and tier-B WASM
/// compile against (Ring0_Build_Plan §1.7).
pub fn emit_rule_module(rule: &RuleDesc) -> TokenStream {
    let mod_name = format_ident!("rule_{}", to_snake(&rule.name));
    let rule_name = &rule.name;

    let delta_fns = rule.delta_sources.iter().map(|src| {
        let fn_name = format_ident!("delta_from_{}", to_snake(src));
        let doc = format!("Semi-naive delta of `{rule_name}` driven by a change to `{src}`.");
        quote! {
            #[doc = #doc]
            pub fn #fn_name(/* delta batch: &DeltaBatch */) /* -> Emissions */ {
                // brixc emit: join plan lowered from brix-ir + meta.Plan goes here.
                todo!("delta body emitted once brix-ir join plans land")
            }
        }
    });

    quote! {
        pub mod #mod_name {
            use super::*;

            #( #delta_fns )*
        }
    }
}

/// Format a token stream through prettyplease — the canonical formatter for
/// generated Rust, so codegen snapshots are stable and reviewable. Returns the
/// unformatted debug text if the tokens don't parse as a Rust file (only possible
/// on a codegen bug; surfaced rather than hidden).
pub fn format_tokens(tokens: TokenStream) -> String {
    match syn::parse2::<syn::File>(tokens.clone()) {
        Ok(file) => prettyplease::unparse(&file),
        Err(e) => format!("/* brixc codegen produced invalid Rust: {e} */\n{tokens}"),
    }
}

/// Emit a whole generated crate root: determinism header + every relation and
/// rule module. This is the unit the flagship's `insta` snapshot covers.
pub fn emit_crate_root(relations: &[RelationDesc], rules: &[RuleDesc]) -> String {
    let header = determinism_header();
    let rel_mods = relations.iter().map(emit_relation_module);
    let rule_mods = rules.iter().map(emit_rule_module);
    let tokens = quote! {
        #header
        #( #rel_mods )*
        #( #rule_mods )*
    };
    format_tokens(tokens)
}

/// snake_case a PascalCase / mixed identifier for module and fn names. A
/// real Core IR relation name can be dotted (a protocol's synthesized
/// `Protocol.Outcome` relation, e.g. `AssignOrder.Chosen`) — any character
/// that can't stand in a Rust identifier becomes `_` rather than being
/// passed through into an invalid `format_ident!` call.
fn to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_ascii_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// Strip qualifier separators from a dotted relation name for use in a
/// PascalCase Rust identifier. Segments are already PascalCase, so
/// straight concatenation reads naturally: `AssignOrder.Chosen` ->
/// `AssignOrderChosen`.
fn to_pascal_ident(s: &str) -> String {
    s.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_')
        .collect()
}

/// Build an ident from `s`, escaping it as a raw identifier (`r#ref`) if
/// `s` collides with a Rust keyword — a real role name can be exactly one
/// (`key ref: String`, Part IV §1, is legal BrixMS and a reserved word in
/// Rust). Unprefixed `format_ident!` idents (`rel_`/`rule_`/`delta_from_`)
/// never hit this since the prefix always makes them non-keywords.
fn safe_ident(s: &str) -> proc_macro2::Ident {
    if syn::parse_str::<syn::Ident>(s).is_ok() {
        format_ident!("{}", s)
    } else {
        format_ident!("r#{}", s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn order_status() -> RelationDesc {
        RelationDesc {
            name: "OrderStatus".into(),
            columns: vec![
                ColumnDesc {
                    name: "order".into(),
                    rust_type: "NodeId".into(),
                },
                ColumnDesc {
                    name: "value".into(),
                    rust_type: "i64".into(),
                },
            ],
            key: vec!["order".into()],
        }
    }

    #[test]
    fn header_denies_hashmap_and_unsafe() {
        let s = format_tokens(determinism_header());
        assert!(s.contains("deny(unsafe_code)"));
        assert!(s.contains("disallowed_types"));
        assert!(s.contains("float_arithmetic"));
    }

    #[test]
    fn relation_module_uses_btreemap_not_hashmap() {
        let s = format_tokens(emit_relation_module(&order_status()));
        assert!(s.contains("mod rel_order_status"));
        assert!(s.contains("struct OrderStatusRow"));
        assert!(s.contains("BTreeMap"));
        assert!(!s.contains("HashMap"));
    }

    #[test]
    fn rule_module_has_one_delta_fn_per_source() {
        let rule = RuleDesc {
            name: "Waiting".into(),
            delta_sources: vec!["OrderStatus".into(), "Delivered".into()],
            target_relation: None,
            identity_source: None,
            phase: 0,
        };
        let s = format_tokens(emit_rule_module(&rule));
        assert!(s.contains("mod rule_waiting"));
        assert!(s.contains("fn delta_from_order_status"));
        assert!(s.contains("fn delta_from_delivered"));
    }

    #[test]
    fn crate_root_parses_and_is_stable() {
        let rels = [order_status()];
        let rules = [RuleDesc {
            name: "Waiting".into(),
            delta_sources: vec!["OrderStatus".into()],
            target_relation: None,
            identity_source: None,
            phase: 0,
        }];
        let a = emit_crate_root(&rels, &rules);
        let b = emit_crate_root(&rels, &rules);
        // Deterministic codegen: same descriptors in, byte-identical Rust out.
        assert_eq!(a, b);
        // And it is a parseable Rust file (format_tokens would have wrapped an
        // error in a comment otherwise).
        assert!(!a.contains("produced invalid Rust"));
    }

    #[test]
    fn runtime_emission_fails_closed_for_non_identity_rules() {
        let rules = [RuleDesc {
            name: "Join".into(),
            delta_sources: vec!["Input".into(), "Other".into()],
            target_relation: Some("Output".into()),
            identity_source: None,
            phase: 0,
        }];
        assert_eq!(unsupported_runtime_rules(&rules), vec!["Join"]);
    }
}
